### ISSUE TITLE
After installing Atom by pressing on the Alt key the menu bar disappears...

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/atom-cloudslang-package#36]
After installing Atom by pressing the Alt key (the menu bar disappears …) – no way of knowing it’s the Alt key… we should document it although it's related to Atom

**Comment by oritstone** [comment]
Not sure that we should mention it in our docs...

**Comment by meshipeer** [comment]
do we have link to Atom documentation \ project that contains also their issues?
if so i think we can close this

**Comment by oritstone** [comment]
We don' have a link to their issues.
We can add a link to their FAQ: https://discuss.atom.io
Is it good enough?

**Comment by roieyal** [comment]
I think it's good (the issue is in there...)
