### ISSUE TITLE
Couldn’t understand how to configure the proxy on my windows….

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/atom-cloudslang-package#38]
![atom2](https://cloud.githubusercontent.com/assets/10178900/11561147/ffbdef7c-99cd-11e5-8335-4baddec81b65.jpg)

**Comment by oritstone** [comment]
I do not think it should be part of our package documentation.
It is a pure Atom configuration issue, not related to our package

**Comment by roieyal** [comment]
the proxy atom configuration is mentioned in our package at:
https://github.com/CloudSlang/atom-cloudslang-package/
we should add windows configuration as well

**Comment by SamMarkowitz** [comment]
It works for windows. I've done it. The file they mention in their docs didn't exist, but I just created it where it was supposed to be. 

Their documentation wasn't that great, but I'm still not sure we want to reproduce it (with improvement of course) in our own docs.
