### ISSUE TITLE
parallel_loop is not atom-recognized keyword

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/atom-cloudslang-package#92]
Type 'parallel_loop' in an .sl file in Atom
It is not recognized as a cslang keyword (async_loop is)

**Comment by levice14** [comment]
are you using latest version? v.0.3.0 should fix this problem

https://github.com/CloudSlang/atom-cloudslang-package/pull/83

**Comment by dumagalex** [comment]
You're right, works fine with v.0.3.0

**Comment by levice14** [comment]
thanks - closing
